#!/usr/bin/env bash

# Assuming Ubuntu install, please install pip3 otherwise

[[ "$(apt version > /dev/null 2>&1 ; echo $?)" ]] && (sudo apt-get install pip3 -y) || (echo "Architecture not Debian, aborting";exit)

# Proper libraries installed

declare -a array=('google-api-python-client' 'google-auth-httplib2' 'google-auth-oauthlib' 'selenium' 'beautifulsoup4')

for package in "${array[@]}"; do
	pip3 install --upgrade "$package"
done

# Proper directory structure

APP_LOCATION="$HOME/Applications/starbucks_automa"

[[ ! -d "$APP_LOCATION" ]] && mkdir -p "$APP_LOCATION"/{configuration,credentials,work_schedules}

# Credentials

[[ -f ./credentials.tar ]] && (tar -xvf credentials.tar -C "$APP_LOCATION"/credentials) || (echo "[-] Please provide credentials before running the program")

# Installing starbucks_automa

[[ ! -d /usr/lib/python3/dist-packages/starbucksautoma ]] && (sudo mkdir -p /usr/lib/python3/dist-packages/starbucksautoma)

[[ -f ./starbucks_automa_installer.tar ]] && (sudo tar -xvf starbucks_automa_installer.tar --strip-components=1)

# Test if it was successfully installed

starbucksautoma --version
